# -*- mode: ruby -*-
# vi: set ft=ruby :

# created by: Jeremy Kuhnash, Mesosphere
#
#  Built for testing Oracle Linux 7.3 as a platform for infrastructure software, particularly Mesosphere DC/OS.
#  No warranties applied. Refer to Apache License 2.0 for licensing.

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "oel73" do |base|
    base.vm.box = "box-cutter/ol73"
    base.vm.network :private_network, ip: "192.168.56.200"
    base.vm.provider "virtualbox" do |vb|
      vb.name = "oel73_3.10"
      vb.memory = "1024"
      vb.cpus = "2"
      file_to_disk = File.realpath( "." ).to_s + '/disk2.vdi'
      file_exists = File.exist?(file_to_disk)
      unless file_exists
        # print "Doesnt exist? -- " + File.exist?(masterfile_to_disk)
        vb.customize ['createhd', '--filename', file_to_disk, '--variant', 'Standard', '--size', 42 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
      vb.customize ["modifyvm", :id, "--name", "oel73_3.10"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    base.vm.provision "shell",
      path: "docker_install.sh"
    base.vm.provision "shell",
      path: "kernel_3.10.sh"
    base.vm.provision "shell",
      path: "system_services.sh"
  end
end
