#!/bin/bash
#set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
BENCH_TOOLS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
echo "Tools Dir: $BENCH_TOOLS_DIR"
# The below seems to be fixed in versions after 0.4.5
rm -fR ~/.dcos/clusters/
if [ -z "$CCM_USER" ] || [ -z "$CCM_PASSWORD" ]; then
    echo "Please set both CCM_USER and CCM_PASSWORD in your environment using export or set."
    exit 1
fi
dcos cluster setup $1 --insecure  --username=${CCM_USER} --password=${CCM_PASSWORD}
dcos package install --cli dcos-enterprise-cli --yes
export PUBLIC_AGENT="$(${BENCH_TOOLS_DIR}/get_public_ip.sh)"
echo "Public Agent: $PUBLIC_AGENT"
#dcos node ssh --master-proxy --leader
