bootstrap_url: http://192.168.56.100:80
cluster_name: 'DCOS-VAGRANT'
customer_key: 4f03f0ec-5632-7982-ab82-0d17244c2b1e
exhibitor_storage_backend: static
master_discovery: static
master_list:
- 192.168.56.101
resolvers:
- 8.8.8.8
# Choose your security mode: permissive, strict, or disabled
security: permissive
# password is Bam456Bam
superuser_password_hash: $6$rounds=656000$Ws6LBsL6SOmNWb8v$3ZrVQVHkXRNFDGY9AU/XpvaCy4NB543rudxx3LaBcW1R.f1vkHOEoQHl2W9wSCgA.dMDclWYam6..mOZd7ct30
superuser_username: console
use_proxy: 'false'
telemetry_enabled: 'false'
dcos_overlay_enable: 'false'
log_directory: /genconf/logs
mesos_dns_ip_sources:
 - netinfo
 - host
